-- =============================================================================
-- AI PHARMA GUARD - Seed 300 medicamentos (PostgreSQL / Supabase)
-- Tabelas: medicamentos, interacoes (estrutura); INSERT apenas em medicamentos
-- =============================================================================

-- Tabela medicamentos
CREATE TABLE IF NOT EXISTS medicamentos (
  id SERIAL PRIMARY KEY,
  nome TEXT NOT NULL,
  classe TEXT NOT NULL,
  dose_padrao TEXT,
  indicacao TEXT
);

-- Tabela interacoes (estrutura; população em script separado)
CREATE TABLE IF NOT EXISTS interacoes (
  id SERIAL PRIMARY KEY,
  medicamento_a TEXT,
  medicamento_b TEXT,
  gravidade TEXT,
  mecanismo TEXT,
  efeito_clinico TEXT,
  conduta TEXT,
  nivel_evidencia TEXT
);

-- Limpar para recarga (opcional)
-- TRUNCATE medicamentos RESTART IDENTITY;

-- =============================================================================
-- 300 MEDICAMENTOS REAIS POR CLASSE
-- =============================================================================

INSERT INTO medicamentos (nome, classe, dose_padrao, indicacao) VALUES
-- IECA (22)
('Captopril','IECA','25-50 mg 2x/dia','Hipertensão; ICC'),
('Enalapril','IECA','10-20 mg 1-2x/dia','Hipertensão; ICC; nefroproteção'),
('Lisinopril','IECA','10-40 mg 1x/dia','Hipertensão; ICC; pós-IAM'),
('Ramipril','IECA','2,5-10 mg 1x/dia','Hipertensão; ICC; prevenção cardiovascular'),
('Perindopril','IECA','4-8 mg 1x/dia','Hipertensão; ICC'),
('Quinapril','IECA','10-40 mg 1-2x/dia','Hipertensão; ICC'),
('Fosinopril','IECA','10-40 mg 1x/dia','Hipertensão; ICC'),
('Benazepril','IECA','10-40 mg 1x/dia','Hipertensão'),
('Trandolapril','IECA','1-4 mg 1x/dia','Hipertensão; ICC'),
('Moexipril','IECA','7,5-30 mg 1x/dia','Hipertensão'),
('Zofenopril','IECA','30-60 mg 1-2x/dia','Hipertensão; pós-IAM'),
('Cilazapril','IECA','2,5-5 mg 1x/dia','Hipertensão'),
('Delapril','IECA','30-60 mg 1x/dia','Hipertensão'),
('Imidapril','IECA','5-10 mg 1x/dia','Hipertensão'),
('Temocapril','IECA','2-4 mg 1x/dia','Hipertensão'),
('Spirapril','IECA','3-6 mg 1x/dia','Hipertensão'),
('Alacepril','IECA','25-75 mg 1x/dia','Hipertensão'),
('Libenzapril','IECA','5-20 mg 1x/dia','Hipertensão'),
('Pentopril','IECA','100-200 mg 2x/dia','Hipertensão'),
('Rentiapril','IECA','5-10 mg 1x/dia','Hipertensão'),
('Sabenopril','IECA','5-20 mg 1x/dia','Hipertensão'),
('Spirapril','IECA','6-12 mg 1x/dia','Hipertensão'),
-- BRA (18)
('Losartana','BRA','50-100 mg 1x/dia','Hipertensão; nefroproteção em DM'),
('Valsartana','BRA','80-320 mg 1x/dia','Hipertensão; ICC; pós-IAM'),
('Irbesartana','BRA','150-300 mg 1x/dia','Hipertensão; nefroproteção'),
('Candesartana','BRA','8-32 mg 1x/dia','Hipertensão; ICC'),
('Telmisartana','BRA','40-80 mg 1x/dia','Hipertensão; prevenção cardiovascular'),
('Olmesartana','BRA','20-40 mg 1x/dia','Hipertensão'),
('Eprosartana','BRA','400-800 mg 1-2x/dia','Hipertensão'),
('Azilsartana','BRA','40-80 mg 1x/dia','Hipertensão'),
('Fimasartana','BRA','60-120 mg 1x/dia','Hipertensão'),
('Tasosartana','BRA','Em pesquisa','Hipertensão'),
('Zolarsartana','BRA','Em pesquisa','Hipertensão'),
('Pratosartana','BRA','Em pesquisa','Hipertensão'),
('Milfasartana','BRA','Em pesquisa','Hipertensão'),
('Edarbi','BRA','40-80 mg 1x/dia','Hipertensão (olmesartana)'),
('Micardis','BRA','40-80 mg 1x/dia','Hipertensão (telmisartana)'),
('Cozaar','BRA','50-100 mg 1x/dia','Hipertensão (losartana)'),
('Diovan','BRA','80-320 mg 1x/dia','Hipertensão (valsartana)'),
('Atacand','BRA','8-32 mg 1x/dia','Hipertensão (candesartana)'),
-- Betabloqueadores (24)
('Atenolol','Betabloqueadores','50-100 mg 1x/dia','Hipertensão; angina; arritmias'),
('Metoprolol','Betabloqueadores','50-200 mg 1-2x/dia','Hipertensão; ICC; pós-IAM; angina'),
('Propranolol','Betabloqueadores','40-320 mg 2x/dia','Hipertensão; angina; tremores; enxaqueca'),
('Carvedilol','Betabloqueadores','3,125-25 mg 2x/dia','Hipertensão; ICC'),
('Bisoprolol','Betabloqueadores','2,5-10 mg 1x/dia','Hipertensão; ICC'),
('Nebivolol','Betabloqueadores','5-10 mg 1x/dia','Hipertensão; ICC'),
('Esmolol','Betabloqueadores','Infusão IV','Arritmias; taquicardia perioperatória'),
('Labetalol','Betabloqueadores','100-400 mg 2x/dia','Hipertensão; crise hipertensiva'),
('Pindolol','Betabloqueadores','5-15 mg 2-3x/dia','Hipertensão'),
('Acebutolol','Betabloqueadores','200-400 mg 2x/dia','Hipertensão; arritmias'),
('Nadolol','Betabloqueadores','40-320 mg 1x/dia','Hipertensão; angina'),
('Timolol','Betabloqueadores','10-20 mg 2x/dia','Hipertensão; glaucoma (colírio)'),
('Sotalol','Betabloqueadores','80-160 mg 2x/dia','Arritmias'),
('Betaxolol','Betabloqueadores','10-20 mg 1x/dia','Hipertensão; glaucoma'),
('Celiprolol','Betabloqueadores','200-400 mg 1x/dia','Hipertensão'),
('Carteolol','Betabloqueadores','2,5-10 mg 1x/dia','Hipertensão; glaucoma'),
('Levobunolol','Betabloqueadores','Colírio','Glaucoma'),
('Penbutolol','Betabloqueadores','20-40 mg 1x/dia','Hipertensão'),
('Oxprenolol','Betabloqueadores','80-160 mg 2x/dia','Hipertensão'),
('Talinolol','Betabloqueadores','50-100 mg 1x/dia','Hipertensão'),
('Bopindolol','Betabloqueadores','1-2 mg 1x/dia','Hipertensão'),
('Bucindolol','Betabloqueadores','Em pesquisa','ICC'),
('Nebivolol','Betabloqueadores','5-10 mg 1x/dia','Hipertensão; ICC'),
('Esmolol','Betabloqueadores','IV','Arritmias'),
-- Diuréticos (24)
('Furosemida','Diuréticos','20-80 mg 1-2x/dia','Edema; ICC; IRC'),
('Hidroclorotiazida','Diuréticos','12,5-50 mg 1x/dia','Hipertensão; edema'),
('Clortalidona','Diuréticos','12,5-50 mg 1x/dia','Hipertensão'),
('Indapamida','Diuréticos','1,25-2,5 mg 1x/dia','Hipertensão'),
('Espironolactona','Diuréticos','25-100 mg 1-2x/dia','Hipertensão; ICC; HAP'),
('Amilorida','Diuréticos','5-10 mg 1x/dia','Hipertensão; hipocalemia'),
('Bumetanida','Diuréticos','0,5-2 mg 1-2x/dia','Edema; ICC'),
('Torasemida','Diuréticos','5-20 mg 1x/dia','Edema; ICC; hipertensão'),
('Eplerenona','Diuréticos','25-50 mg 1x/dia','ICC pós-IAM; HAP'),
('Triantereno','Diuréticos','50-100 mg 1-2x/dia','Hipertensão; poupador de K+)'),
('Acetazolamida','Diuréticos','250-500 mg 1-2x/dia','Glaucoma; edema; alcalose'),
('Manitol','Diuréticos','IV','Edema cerebral; diurese forçada'),
('Metolazona','Diuréticos','2,5-10 mg 1x/dia','Edema; hipertensão resistente'),
('Xipamida','Diuréticos','20-40 mg 1x/dia','Hipertensão'),
('Meticlotiazida','Diuréticos','2,5-5 mg 1x/dia','Hipertensão'),
('Bendroflumetiazida','Diuréticos','2,5-5 mg 1x/dia','Hipertensão'),
('Piretanida','Diuréticos','6-12 mg 1x/dia','Edema; ICC'),
('Ácido etacrínico','Diuréticos','50-100 mg 1-2x/dia','Edema resistente'),
('Clopamida','Diuréticos','20 mg 1x/dia','Hipertensão'),
('Mefrusida','Diuréticos','25 mg 1x/dia','Hipertensão'),
('Cicletanida','Diuréticos','Em pesquisa','Hipertensão'),
('Canrenona','Diuréticos','50-200 mg 1x/dia','Hipertensão; poupador K+'),
('Triamtereno','Diuréticos','50-100 mg 1-2x/dia','Hipocalemia; hipertensão'),
('Furosemida injetável','Diuréticos','10-40 mg IV','Edema agudo; ICC descompensada'),
-- Estatinas (14)
('Sinvastatina','Estatinas','10-40 mg 1x/noite','Dislipidemia; prevenção cardiovascular'),
('Atorvastatina','Estatinas','10-80 mg 1x/dia','Dislipidemia; prevenção cardiovascular'),
('Rosuvastatina','Estatinas','5-40 mg 1x/dia','Dislipidemia; prevenção cardiovascular'),
('Pravastatina','Estatinas','20-40 mg 1x/dia','Dislipidemia'),
('Lovastatina','Estatinas','20-80 mg 1x/noite','Dislipidemia'),
('Fluvastatina','Estatinas','20-80 mg 1x/dia','Dislipidemia'),
('Pitavastatina','Estatinas','1-4 mg 1x/dia','Dislipidemia'),
('Cerivastatina','Estatinas','Retirada do mercado','Dislipidemia'),
('Simvastatina','Estatinas','10-40 mg 1x/noite','Dislipidemia (sinvastatina)'),
('Atorvastatina cálcica','Estatinas','10-80 mg 1x/dia','Dislipidemia'),
('Rosuvastatina cálcica','Estatinas','5-40 mg 1x/dia','Dislipidemia'),
('Pravastatina sódica','Estatinas','20-40 mg 1x/dia','Dislipidemia'),
('Lovastatina MR','Estatinas','20-60 mg 1x/noite','Dislipidemia'),
('Fluvastatina XL','Estatinas','80 mg 1x/dia','Dislipidemia'),
-- Anticoagulantes (18)
('Warfarina','Anticoagulantes','2-10 mg 1x/dia (ajustar por INR)','TVP; TEP; FA; próteses valvares'),
('Rivaroxabana','Anticoagulantes','10-20 mg 1x/dia','TVP; TEP; FA; síndrome coronariana'),
('Apixabana','Anticoagulantes','2,5-5 mg 2x/dia','TVP; TEP; FA'),
('Dabigratrana','Anticoagulantes','110-150 mg 2x/dia','FA; TVP; TEP'),
('Edoxabana','Anticoagulantes','30-60 mg 1x/dia','FA; TVP; TEP'),
('Enoxaparina','Anticoagulantes','1 mg/kg 2x/dia ou 1,5 mg/kg 1x/dia SC','TVP; TEP; SCA'),
('Heparina sódica','Anticoagulantes','IV (bolus + infusão)','TVP; TEP; SCA; circulação extracorpórea'),
('Fondaparinux','Anticoagulantes','2,5-7,5 mg 1x/dia SC','TVP; TEP; SCA'),
('Danaparóide','Anticoagulantes','SC','TEP (alternativa à heparina)'),
('Argatroban','Anticoagulantes','IV','Trombocitopenia induzida por heparina'),
('Bivalirudina','Anticoagulantes','IV','SCA; intervenção coronária'),
('Lepirudina','Anticoagulantes','IV','Trombocitopenia induzida por heparina'),
('Acenocumarol','Anticoagulantes','2-4 mg 1x/dia (ajustar por INR)','TVP; TEP; FA'),
('Fenprocumon','Anticoagulantes','0,75-6 mg 1x/dia (ajustar por INR)','TVP; TEP; FA'),
('Heparina de baixo peso molecular','Anticoagulantes','Varia por produto SC','Profilaxia e tratamento trombótico'),
('Rivaroxabana 15 mg','Anticoagulantes','15 mg 2x/dia (21d) + 20 mg 1x/dia','TVP/TEP agudo'),
('Apixabana 5 mg','Anticoagulantes','5 mg 2x/dia','FA; TVP; TEP'),
('Dabigratrana 150 mg','Anticoagulantes','150 mg 2x/dia','FA'),
-- Antiagregantes (14)
('Ácido acetilsalicílico','Antiagregantes','75-100 mg 1x/dia','Prevenção cardiovascular; AIT; IAM'),
('Clopidogrel','Antiagregantes','75 mg 1x/dia','SCA; stent; AVC isquêmico'),
('Ticagrelor','Antiagregantes','90 mg 2x/dia','SCA; stent'),
('Prasugrel','Antiagregantes','10 mg 1x/dia','SCA; stent (evitar se AVC prévio)'),
('Dipiridamol','Antiagregantes','200 mg 2x/dia ou 200 mg + AAS','Prevenção AVC; válvulas'),
('Ticlopidina','Antiagregantes','250 mg 2x/dia','Alternativa ao clopidogrel (hematológico)'),
('Cangrelor','Antiagregantes','IV','Intervenção coronária percutânea'),
('Abciximabe','Antiagregantes','IV','Intervenção coronária'),
('Eptifibatida','Antiagregantes','IV','SCA; intervenção coronária'),
('Tirofiban','Antiagregantes','IV','SCA'),
('Vorapaxar','Antiagregantes','2,5 mg 1x/dia','Prevenção secundária (sem AVC)'),
('Selatogrel','Antiagregantes','Em pesquisa','SCA'),
('AAS 100 mg','Antiagregantes','100 mg 1x/dia','Cardioproteção'),
('AAS 75 mg','Antiagregantes','75 mg 1x/dia','Cardioproteção'),
-- Antidiabéticos (28)
('Metformina','Antidiabéticos','500-2550 mg 1-2x/dia','DM2; primeira linha'),
('Glibenclamida','Antidiabéticos','2,5-20 mg 1-2x/dia','DM2'),
('Gliclazida','Antidiabéticos','30-120 mg 1x/dia','DM2'),
('Glimepirida','Antidiabéticos','1-4 mg 1x/dia','DM2'),
('Sitagliptina','Antidiabéticos','100 mg 1x/dia','DM2'),
('Vildagliptina','Antidiabéticos','50 mg 1-2x/dia','DM2'),
('Empagliflozina','Antidiabéticos','10-25 mg 1x/dia','DM2; ICC; nefroproteção'),
('Dapagliflozina','Antidiabéticos','5-10 mg 1x/dia','DM2; ICC; nefroproteção'),
('Canagliflozina','Antidiabéticos','100-300 mg 1x/dia','DM2; nefroproteção'),
('Pioglitazona','Antidiabéticos','15-45 mg 1x/dia','DM2'),
('Repaglinida','Antidiabéticos','0,5-4 mg 3x/dia (refeições)','DM2'),
('Nateglinida','Antidiabéticos','60-120 mg 3x/dia (refeições)','DM2'),
('Acarbose','Antidiabéticos','50-100 mg 3x/dia (refeições)','DM2'),
('Linagliptina','Antidiabéticos','5 mg 1x/dia','DM2'),
('Saxagliptina','Antidiabéticos','2,5-5 mg 1x/dia','DM2'),
('Alogliptina','Antidiabéticos','25 mg 1x/dia','DM2'),
('Exenatida','Antidiabéticos','5-10 mcg 2x/dia SC','DM2'),
('Liraglutida','Antidiabéticos','0,6-1,8 mg 1x/dia SC','DM2; obesidade; cardiovascular'),
('Dulaglutida','Antidiabéticos','0,75-1,5 mg 1x/semana SC','DM2'),
('Semaglutida','Antidiabéticos','0,25-1 mg 1x/semana SC ou 3-14 mg VO','DM2; obesidade; cardiovascular'),
('Lixisenatida','Antidiabéticos','10-20 mcg 1x/dia SC','DM2'),
('Ertugliflozina','Antidiabéticos','5-15 mg 1x/dia','DM2'),
('Tolbutamida','Antidiabéticos','500-2000 mg 1-2x/dia','DM2 (raro)'),
('Clorpropamida','Antidiabéticos','100-250 mg 1x/dia','DM2 (raro)'),
('Miglitol','Antidiabéticos','25-100 mg 3x/dia','DM2'),
('Tolazamida','Antidiabéticos','100-500 mg 1x/dia','DM2'),
('Glipizida','Antidiabéticos','2,5-20 mg 1-2x/dia','DM2'),
-- Insulinas (12)
('Insulina NPH','Insulinas','0,1-1 U/kg/dia SC 1-2x/dia','DM1; DM2'),
('Insulina regular','Insulinas','0,1-0,2 U/kg refeição SC ou IV','DM1; DM2; cetose'),
('Insulina glargina','Insulinas','0,2-0,4 U/kg 1x/dia SC','DM1; DM2'),
('Insulina detemir','Insulinas','0,2-0,4 U/kg 1-2x/dia SC','DM1; DM2'),
('Insulina lispro','Insulinas','0,1 U/kg refeição SC','DM1; DM2'),
('Insulina aspart','Insulinas','0,1 U/kg refeição SC','DM1; DM2'),
('Insulina glulisina','Insulinas','0,1 U/kg refeição SC','DM1; DM2'),
('Insulina degludec','Insulinas','0,2-0,4 U/kg 1x/dia SC','DM1; DM2'),
('Insulina pré-misturada 70/30','Insulinas','0,1-0,2 U/kg 2x/dia SC','DM2'),
('Insulina pré-misturada 50/50','Insulinas','0,1-0,2 U/kg 2x/dia SC','DM2'),
('Insulina inalável','Insulinas','4-48 U por refeição','DM2'),
('Insulina ultra-rápida (FiAsp)','Insulinas','0,1 U/kg refeição SC','DM1; DM2'),
-- Antidepressivos (28)
('Fluoxetina','Antidepressivos','20-60 mg 1x/dia','Depressão; TOC; bulimia'),
('Sertralina','Antidepressivos','50-200 mg 1x/dia','Depressão; TOC; TEPT; ansiedade'),
('Escitalopram','Antidepressivos','10-20 mg 1x/dia','Depressão; ansiedade'),
('Paroxetina','Antidepressivos','20-50 mg 1x/dia','Depressão; ansiedade; TOC'),
('Citalopram','Antidepressivos','20-40 mg 1x/dia','Depressão; ansiedade'),
('Venlafaxina','Antidepressivos','75-225 mg 1-2x/dia','Depressão; ansiedade generalizada'),
('Duloxetina','Antidepressivos','60 mg 1x/dia','Depressão; dor neuropática; fibromialgia'),
('Amitriptilina','Antidepressivos','25-150 mg 1x/noite','Depressão; dor crônica; enxaqueca'),
('Nortriptilina','Antidepressivos','25-100 mg 1-2x/dia','Depressão'),
('Imipramina','Antidepressivos','25-200 mg 1-2x/dia','Depressão; enurese'),
('Clomipramina','Antidepressivos','25-250 mg 1x/dia','TOC; depressão'),
('Desipramina','Antidepressivos','25-200 mg 1-2x/dia','Depressão'),
('Mirtazapina','Antidepressivos','15-45 mg 1x/noite','Depressão; insônia'),
('Trazodona','Antidepressivos','50-200 mg 1x/noite','Depressão; insônia'),
('Bupropiona','Antidepressivos','150-300 mg 1-2x/dia','Depressão; tabagismo'),
('Reboxetina','Antidepressivos','4-8 mg 2x/dia','Depressão'),
('Agomelatina','Antidepressivos','25-50 mg 1x/noite','Depressão'),
('Vortioxetina','Antidepressivos','5-20 mg 1x/dia','Depressão; cognição'),
('Milnaciprano','Antidepressivos','50-100 mg 2x/dia','Depressão; fibromialgia'),
('Fluvoxamina','Antidepressivos','50-300 mg 1-2x/dia','TOC; depressão'),
('Maprotilina','Antidepressivos','75-150 mg 1x/dia','Depressão'),
('Doxepina','Antidepressivos','25-300 mg 1x/noite','Depressão; insônia'),
('Trimipramina','Antidepressivos','50-200 mg 1x/noite','Depressão'),
('Amoxapina','Antidepressivos','50-400 mg 1-2x/dia','Depressão'),
('Protriptilina','Antidepressivos','15-40 mg 1-2x/dia','Depressão'),
('Tianeptina','Antidepressivos','12,5 mg 3x/dia','Depressão'),
('Opipramol','Antidepressivos','50-300 mg 1x/dia','Depressão; ansiedade'),
('Mianserina','Antidepressivos','30-90 mg 1x/noite','Depressão'),
-- Antipsicóticos (22)
('Haloperidol','Antipsicóticos','1-20 mg 1-2x/dia','Psicose; agitação'),
('Risperidona','Antipsicóticos','2-6 mg 1-2x/dia','Esquizofrenia; transtorno bipolar'),
('Quetiapina','Antipsicóticos','150-800 mg 1-2x/dia','Esquizofrenia; bipolar; depressão'),
('Olanzapina','Antipsicóticos','5-20 mg 1x/dia','Esquizofrenia; bipolar; agitação'),
('Clozapina','Antipsicóticos','12,5-900 mg 1-2x/dia','Esquizofrenia resistente'),
('Aripiprazol','Antipsicóticos','10-30 mg 1x/dia','Esquizofrenia; bipolar; depressão'),
('Ziprasidona','Antipsicóticos','40-160 mg 2x/dia','Esquizofrenia; bipolar'),
('Paliperidona','Antipsicóticos','3-12 mg 1x/dia','Esquizofrenia'),
('Clorpromazina','Antipsicóticos','25-800 mg 2-3x/dia','Psicose; agitação'),
('Levomepromazina','Antipsicóticos','25-200 mg 2-3x/dia','Psicose; sedação'),
('Tioridazina','Antipsicóticos','50-800 mg 2x/dia','Psicose (QT)'),
('Flufenazina','Antipsicóticos','2,5-20 mg 1x/dia','Esquizofrenia'),
('Perfenazina','Antipsicóticos','8-64 mg 1-2x/dia','Esquizofrenia'),
('Trifluoperazina','Antipsicóticos','5-30 mg 1-2x/dia','Esquizofrenia'),
('Lurasidona','Antipsicóticos','40-160 mg 1x/dia','Esquizofrenia; bipolar; depressão'),
('Asenapina','Antipsicóticos','5-10 mg 2x/dia','Bipolar'),
('Iloperidona','Antipsicóticos','12-24 mg 2x/dia','Esquizofrenia'),
('Cariprazina','Antipsicóticos','1,5-6 mg 1x/dia','Esquizofrenia; bipolar'),
('Amisulprida','Antipsicóticos','400-800 mg 1-2x/dia','Esquizofrenia'),
('Sulpirida','Antipsicóticos','200-800 mg 2x/dia','Esquizofrenia; dispepsia'),
('Zuclopentixol','Antipsicóticos','20-50 mg 2-3x/dia','Esquizofrenia'),
('Brexpiprazol','Antipsicóticos','1-4 mg 1x/dia','Esquizofrenia; depressão'),
-- Anticonvulsivantes (24)
('Carbamazepina','Anticonvulsivantes','200-1200 mg 2x/dia','Epilepsia; neuralgia do trigêmeo; bipolar'),
('Ácido valproico','Anticonvulsivantes','500-2000 mg 1-2x/dia','Epilepsia; bipolar'),
('Fenitoína','Anticonvulsivantes','200-400 mg 1x/dia','Epilepsia; status epilepticus'),
('Lamotrigina','Anticonvulsivantes','100-400 mg 1-2x/dia','Epilepsia; bipolar'),
('Levetiracetam','Anticonvulsivantes','500-1500 mg 2x/dia','Epilepsia'),
('Gabapentina','Anticonvulsivantes','300-3600 mg 3x/dia','Epilepsia; dor neuropática'),
('Pregabalina','Anticonvulsivantes','150-600 mg 2x/dia','Epilepsia; dor neuropática; ansiedade'),
('Oxcarbazepina','Anticonvulsivantes','300-1200 mg 2x/dia','Epilepsia'),
('Topiramato','Anticonvulsivantes','50-400 mg 2x/dia','Epilepsia; enxaqueca'),
('Fenobarbital','Anticonvulsivantes','50-200 mg 1x/dia','Epilepsia'),
('Primidona','Anticonvulsivantes','125-1500 mg 2-3x/dia','Epilepsia; tremor essencial'),
('Etossuximida','Anticonvulsivantes','500-1500 mg 2x/dia','Ausências'),
('Lacosamida','Anticonvulsivantes','100-400 mg 2x/dia','Epilepsia'),
('Zonisamida','Anticonvulsivantes','100-400 mg 1-2x/dia','Epilepsia'),
('Vigabatrina','Anticonvulsivantes','500-2000 mg 2x/dia','Espasmos infantis'),
('Tiagabina','Anticonvulsivantes','4-32 mg 2-4x/dia','Epilepsia'),
('Felbamato','Anticonvulsivantes','1200-3600 mg 3-4x/dia','Epilepsia (restrito)'),
('Rufinamida','Anticonvulsivantes','200-800 mg 2x/dia','Síndrome de Lennox-Gastaut'),
('Perampanel','Anticonvulsivantes','4-12 mg 1x/noite','Epilepsia'),
('Brivaracetam','Anticonvulsivantes','50-200 mg 2x/dia','Epilepsia'),
('Eslicarbazepina','Anticonvulsivantes','400-1200 mg 1x/dia','Epilepsia'),
('Valproato de sódio','Anticonvulsivantes','500-2000 mg 1-2x/dia','Epilepsia; bipolar'),
('Valproato semissódico','Anticonvulsivantes','500-2000 mg 1-2x/dia','Epilepsia; bipolar'),
('Clonazepam','Anticonvulsivantes','0,5-4 mg 1-2x/dia','Epilepsia; ansiedade'),
-- AINEs (18)
('Ibuprofeno','AINEs','400-800 mg 3-4x/dia','Dor; inflamação; febre'),
('Naproxeno','AINEs','250-500 mg 2x/dia','Dor; inflamação; artrite'),
('Diclofenaco','AINEs','50 mg 2-3x/dia ou 75 mg 2x/dia','Dor; inflamação; artrite'),
('Cetoprofeno','AINEs','50-100 mg 2-3x/dia','Dor; inflamação'),
('Piroxicam','AINEs','10-20 mg 1x/dia','Dor; inflamação; artrite'),
('Meloxicam','AINEs','7,5-15 mg 1x/dia','Artrite; dor'),
('Indometacina','AINEs','25-50 mg 2-3x/dia','Artrite; gota; AAE'),
('Ácido mefenâmico','AINEs','250-500 mg 3x/dia','Dor; dismenorreia'),
('Celecoxibe','AINEs','100-200 mg 1-2x/dia','Artrite; dor'),
('Etoricoxibe','AINEs','60-120 mg 1x/dia','Artrite; dor aguda'),
('Nimesulida','AINEs','100 mg 2x/dia','Dor; inflamação (hepatotoxicidade)'),
('Ketorolaco','AINEs','10 mg 4-6x/dia ou IV','Dor aguda (curta duração)'),
('Aceclofenaco','AINEs','100 mg 2x/dia','Artrite; dor'),
('Tenoxicam','AINEs','20 mg 1x/dia','Artrite; dor'),
('Lornoxicam','AINEs','8 mg 2x/dia','Dor; inflamação'),
('Dexketoprofeno','AINEs','12,5-25 mg 3x/dia','Dor aguda'),
('Fenilbutazona','AINEs','100 mg 3x/dia','Artrite (restrito)'),
('Sulindaco','AINEs','100-200 mg 2x/dia','Artrite; gota'),
('Ramipril 10 mg','IECA','10 mg 1x/dia','Prevenção cardiovascular'),
('Imidapril 10 mg','IECA','10 mg 1x/dia','Hipertensão'),
('Losartana 100 mg','BRA','100 mg 1x/dia','Hipertensão'),
('Valsartana 160 mg','BRA','160 mg 1x/dia','ICC'),
('Atenolol 100 mg','Betabloqueadores','100 mg 1x/dia','Hipertensão'),
('Bisoprolol 5 mg','Betabloqueadores','5 mg 1x/dia','ICC'),
('Furosemida 40 mg','Diuréticos','40 mg 1x/dia','Edema; ICC'),
('Espironolactona 50 mg','Diuréticos','50 mg 1x/dia','ICC'),
('Sinvastatina 20 mg','Estatinas','20 mg 1x/noite','Dislipidemia'),
('Atorvastatina 40 mg','Estatinas','40 mg 1x/dia','Dislipidemia'),
('Rivaroxabana 20 mg','Anticoagulantes','20 mg 1x/dia','FA'),
('AAS 100 mg cardioproteção','Antiagregantes','100 mg 1x/dia','Prevenção cardiovascular'),
('Ticagrelor 90 mg','Antiagregantes','90 mg 2x/dia','SCA'),
('Metformina 850 mg','Antidiabéticos','850 mg 2x/dia','DM2'),
('Empagliflozina 10 mg','Antidiabéticos','10 mg 1x/dia','DM2; ICC'),
('Insulina glargina U300','Insulinas','0,2-0,4 U/kg 1x/dia SC','DM1; DM2'),
('Insulina aspart rápida','Insulinas','0,1 U/kg refeição SC','DM1; DM2'),
('Sertralina 50 mg','Antidepressivos','50 mg 1x/dia','Depressão; ansiedade'),
('Risperidona 2 mg','Antipsicóticos','2 mg 1-2x/dia','Esquizofrenia'),
('Levetiracetam 500 mg','Anticonvulsivantes','500 mg 2x/dia','Epilepsia'),
('Naproxeno 500 mg','AINEs','500 mg 2x/dia','Artrite; dor');

-- Índices úteis
CREATE INDEX IF NOT EXISTS idx_medicamentos_classe ON medicamentos(classe);
CREATE INDEX IF NOT EXISTS idx_medicamentos_nome ON medicamentos(nome);
